kafka:
  listener:
    concurrency: 1
    ack-mode: MANUAL_IMMEDIATE
  auto:
    create:
      topics:
        enable: false
  bootstrapserver: pkc-lq8gm.westeurope.azure.confluent.cloud:9092
  properties:
    saslRequired: true
    schema.sasl.mechanism: true
    ssl.endpoint.identification.algorithm: https
    sasl.mechanism: PLAIN
    request.timeout.ms: 20000
    retry.backoff.ms: 500
    sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username= "LX5UDF5FKEAIHCYC" password="0Zf8HkRMUvSwLKryGYo+Uk2XNIbduktoxMQ2jY2EmBmKx9OnVIYCcm8EUGquoCRE";
    security.protocol: SASL_SSL
    schema.registry.url: https://psrc-4kk0p.westeurope.azure.confluent.cloud/
    basic.auth.credentials.source: USER_INFO
    schema.registry.basic.auth.user.info: I2WOGC3S6UQMR3KT:vk4Th6eSdHoSVhdagDMtQVnqbkWAFCUdoNGcrylSmQMP9uYZwPVIKJy5zNFY5HDk
    max.poll.interval.ms: 300000
    session.timeout.ms: 60000
    heartbeat.interval.ms: 20000
    max.poll.records: 300
  consumer:
    topics:
      gsis-topic: MSK.schedule.datedSchedule.topic.public.any.v5
    groupIds:
      gsis-group-id: MSK.imports.arrivalnoticegsis.consumerGroup.v1
    enable-consumer:
      gsis: true
      bcp: true
    auto-offset-reset: earliest
    gsis-key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    gsis-value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      specific.avro.reader: true