kafka:
  listener:
    concurrency: ${kafka_concurrency}
    ack-mode:${ack-mode}
  auto:
    create:
      topics:
        enable: false
  bootstrapserver: ${kafka-bootstrap-server}
  properties:
    saslRequired: true
    schema.sasl.mechanism: true
    ssl.endpoint.identification.algorithm: https
    sasl.mechanism: PLAIN
    request.timeout.ms: ${kafkaRequestTimeoutMs}
    retry.backoff.ms: ${kafkaRetryBackoffMs}
    sasl.jaas.config: ${sasl_jass_config}
    security.protocol: SASL_SSL
    schema.registry.url: ${schema-registry-url}
    basic.auth.credentials.source: USER_INFO
    schema.registry.basic.auth.user.info: ${schema_registry_auth}
    max.poll.interval.ms: ${maxPollIntervalMsConfig}
    session.timeout.ms: ${sessionTimeoutMsConfig}
    heartbeat.interval.ms: ${heartbeatIntervalMsConfig}
    max.poll.records: ${maxPollRecordsConfig}
  consumer:
    topics:
      gsis-topic: ${response-topic-name}
    groupIds:
      gsis-group-id: ${consumer-group-id}
    enable-consumer:
      gsis: true
      bcp: true
    auto-offset-reset: earliest
    gsis-key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    gsis-value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      specific.avro.reader: true